import { ReportData } from "@/types/schema";

/**
 * Scenario 1: GA4 + GSC only
 * Traffic and SEO modules included, no paid module.
 */
export const scenario1: ReportData = {
  meta: {
    id: "rpt_scenario_1",
    clientName: "Bergström & Co",
    clientDomain: "bergstrom.se",
    agencyName: "Digital Effekt",
    reportType: "full",
    cadence: "monthly",
    period: {
      label: "Mars 2026",
      startDate: "2026-03-01",
      endDate: "2026-03-31",
    },
    availableSources: ["ga4", "gsc"],
    generatedAt: "2026-04-01T08:00:00Z",
  },

  executiveSummary: {
    headline: "SEO levererar. 18 % mer trafik utan att spendera en krona.",
    subheadline: "Synligheten växer månad för månad. Du är på väg upp — håll kursen.",
    paragraphs: [
      "Bergström & Co hade en tydlig ökning i organisk trafik under mars, främst drivet av bättre positioner på köpintensiva produktfrågor. Sessioner från organisk sökning ökade 18 % jämfört med föregående månad.",
      "CTR förbättrades för de flesta bevakade sökorden och flera kategorisidor nådde topp 5 för första gången. Två sidor behöver följas upp på grund av fallande positioner.",
    ],
    highlights: [
      { label: "Organiska sessioner", value: "+18%", sentiment: "positive" },
      { label: "Genomsn. position", value: "11,2 → 9,4", sentiment: "positive" },
      { label: "CTR", value: "3,1%", sentiment: "neutral" },
    ],
    aiSummary: {
      whatHappened: "Organisk trafik ökade 18 % MoM, drivet av bättre positioner inom viktiga produktkategorier.",
      whyItMatters: "Om trenden håller i sig pekar den mot 35-40 % fler organiska leads till Q3.",
      nextStep: "Prioritera innehållsförbättringar på de två kategorisidor som tappar position innan nästa indexeringscykel.",
    },
  },

  kpiSnapshot: {
    period: "Mars 2026",
    comparisonPeriod: "Februari 2026",
    metrics: [
      {
        label: "Totala sessioner",
        value: 24_180,
        previousValue: 20_510,
        unit: "number",
        trend: "up",
        trendGood: true,
      },
      {
        label: "Organiska sessioner",
        value: 16_320,
        previousValue: 13_830,
        unit: "number",
        trend: "up",
        trendGood: true,
      },
      {
        label: "Totala klick",
        value: 8_940,
        previousValue: 7_600,
        unit: "number",
        trend: "up",
        trendGood: true,
      },
      {
        label: "Genomsn. position",
        value: 9.4,
        previousValue: 11.2,
        unit: "number",
        trend: "up",
        trendGood: true,
      },
      {
        label: "CTR",
        value: 3.1,
        previousValue: 2.8,
        unit: "percent",
        trend: "up",
        trendGood: true,
      },
      {
        label: "Avvisningsfrekvens",
        value: 42.3,
        previousValue: 47.1,
        unit: "percent",
        trend: "down",
        trendGood: true,
      },
    ],
  },

  trafficOverview: {
    totalSessions: {
      label: "Totala sessioner",
      value: 24_180,
      previousValue: 20_510,
      unit: "number",
      trend: "up",
      trendGood: true,
    },
    organicSessions: {
      label: "Organisk trafik",
      value: 16_320,
      previousValue: 13_830,
      unit: "number",
      trend: "up",
      trendGood: true,
    },
    directSessions: {
      label: "Direkt",
      value: 4_820,
      previousValue: 4_200,
      unit: "number",
      trend: "up",
      trendGood: true,
    },
    referralSessions: {
      label: "Hänvisningar",
      value: 3_040,
      previousValue: 2_480,
      unit: "number",
      trend: "up",
      trendGood: true,
    },
    bounceRate: {
      label: "Avvisningsfrekvens",
      value: 42.3,
      previousValue: 47.1,
      unit: "percent",
      trend: "down",
      trendGood: true,
    },
    avgSessionDuration: {
      label: "Genomsn. sessionslängd",
      value: 142,
      previousValue: 128,
      unit: "seconds",
      trend: "up",
      trendGood: true,
    },
    timeSeries: [
      { date: "2026-03-01", value: 620 },
      { date: "2026-03-03", value: 810 },
      { date: "2026-03-05", value: 780 },
      { date: "2026-03-07", value: 920 },
      { date: "2026-03-10", value: 860 },
      { date: "2026-03-12", value: 1050 },
      { date: "2026-03-14", value: 990 },
      { date: "2026-03-17", value: 870 },
      { date: "2026-03-19", value: 940 },
      { date: "2026-03-21", value: 1120 },
      { date: "2026-03-24", value: 1080 },
      { date: "2026-03-26", value: 760 },
      { date: "2026-03-28", value: 830 },
      { date: "2026-03-31", value: 900 },
    ],
    channelBreakdown: [
      { channel: "Organisk sökning", sessions: 16_320, share: 67.5 },
      { channel: "Direkt", sessions: 4_820, share: 19.9 },
      { channel: "Hänvisningar", sessions: 3_040, share: 12.6 },
    ],
  },

  seoOverview: {
    totalClicks: {
      label: "Totala klick",
      value: 8_940,
      previousValue: 7_600,
      unit: "number",
      trend: "up",
      trendGood: true,
    },
    totalImpressions: {
      label: "Totala visningar",
      value: 288_000,
      previousValue: 271_000,
      unit: "number",
      trend: "up",
      trendGood: true,
    },
    avgPosition: {
      label: "Genomsn. position",
      value: 9.4,
      previousValue: 11.2,
      unit: "number",
      trend: "up",
      trendGood: true,
    },
    avgCtr: {
      label: "Genomsn. CTR",
      value: 3.1,
      previousValue: 2.8,
      unit: "percent",
      trend: "up",
      trendGood: true,
    },
    timeSeries: [
      { date: "2026-03-01", value: 240, secondaryValue: 8200 },
      { date: "2026-03-03", value: 310, secondaryValue: 9400 },
      { date: "2026-03-05", value: 290, secondaryValue: 8900 },
      { date: "2026-03-07", value: 340, secondaryValue: 10200 },
      { date: "2026-03-10", value: 320, secondaryValue: 9800 },
      { date: "2026-03-12", value: 410, secondaryValue: 11600 },
      { date: "2026-03-14", value: 380, secondaryValue: 10800 },
      { date: "2026-03-17", value: 350, secondaryValue: 10100 },
      { date: "2026-03-19", value: 370, secondaryValue: 10500 },
      { date: "2026-03-21", value: 430, secondaryValue: 12300 },
      { date: "2026-03-24", value: 420, secondaryValue: 12100 },
      { date: "2026-03-26", value: 280, secondaryValue: 8600 },
      { date: "2026-03-28", value: 310, secondaryValue: 9200 },
      { date: "2026-03-31", value: 340, secondaryValue: 10600 },
    ],
    topQueries: [
      { query: "bergström kontorsmöbler", clicks: 1240, impressions: 18400, position: 2.1, ctr: 6.7 },
      { query: "kontorsstolar ergonomiska", clicks: 890, impressions: 24200, position: 4.8, ctr: 3.7 },
      { query: "skrivbord höjdjusterbart", clicks: 720, impressions: 19800, position: 5.2, ctr: 3.6 },
      { query: "kontor inredning stockholm", clicks: 540, impressions: 28100, position: 7.4, ctr: 1.9 },
      { query: "möbler för kontor", clicks: 480, impressions: 22400, position: 8.1, ctr: 2.1 },
    ],
  },

  topPages: {
    pages: [
      { url: "/kontorsstolar", title: "Ergonomiska kontorsstolar", sessions: 4_280, clicks: 2_140, impressions: 42_000, position: 3.2, bounceRate: 38.1, trend: "up" },
      { url: "/skrivbord", title: "Höjdjusterbara skrivbord", sessions: 3_120, clicks: 1_680, impressions: 31_000, position: 4.7, bounceRate: 41.4, trend: "up" },
      { url: "/", title: "Hem", sessions: 2_840, clicks: 820, impressions: 14_200, position: 8.3, bounceRate: 52.1, trend: "flat" },
      { url: "/om-oss", title: "Om oss", sessions: 1_920, clicks: 290, impressions: 8_100, position: 12.1, bounceRate: 44.7, trend: "down" },
      { url: "/kontakt", title: "Kontakt", sessions: 1_640, clicks: 180, impressions: 6_400, position: 14.8, bounceRate: 35.9, trend: "flat" },
    ],
  },

  issues: [
    {
      id: "iss_001",
      severity: "warning",
      category: "SEO",
      title: "H1 saknas på tre kategorisidor",
      description: "Tre kategorisidor saknar en tydlig H1-rubrik, vilket kan minska sidornas relevanssignaler i sök.",
      pagesAffected: 3,
      impact: "medium",
    },
    {
      id: "iss_002",
      severity: "info",
      category: "Prestanda",
      title: "Produktbilder saknar alt-texter",
      description: "14 produktbilder saknar beskrivande alt-text, vilket påverkar både tillgänglighet och bildsök.",
      pagesAffected: 14,
      impact: "low",
    },
    {
      id: "iss_003",
      severity: "warning",
      category: "SEO",
      title: "Två sidor tappar position",
      description: "/om-oss och /leverans tappade mer än tre positioner i mars. Innehållets aktualitet bör ses över.",
      pagesAffected: 2,
      impact: "medium",
    },
  ],

  recommendations: [
    {
      id: "rec_001",
      priority: 1,
      category: "SEO",
      action: "Lägg till H1-rubriker på de tre berörda kategorisidorna",
      rationale: "Saknade H1:or skapar otydlighet för sökmotorer och kan dämpa rankning. Låg insats, tydlig effekt.",
      effort: "low",
      impact: "high",
      source: "gsc",
    },
    {
      id: "rec_002",
      priority: 2,
      category: "Innehåll",
      action: "Uppdatera innehållet på /om-oss och /leverans",
      rationale: "Båda sidorna tappade position i mars. Uppdaterat innehåll och strukturerad data kan vända utvecklingen.",
      effort: "medium",
      impact: "medium",
      source: "gsc",
    },
    {
      id: "rec_003",
      priority: 3,
      category: "Tillgänglighet",
      action: "Lägg till alt-texter på alla produktbilder",
      rationale: "Förbättrar tillgänglighet och stärker möjligheten att synas i bildsök.",
      effort: "low",
      impact: "low",
      source: "ga4",
    },
  ],
};
