import { DashboardDefinition } from "@/types/dashboard";

export const dashboardRegistry: DashboardDefinition[] = [
  {
    id: "ai-summary-hero",
    name: "AI Summary Hero",
    type: "hero",
    requiredSources: [],
    optionalSources: ["ga4", "gsc", "google_ads"],
    requiredDataFields: ["executiveSummary.headline"],
    optionalDataFields: [
      "executiveSummary.subheadline",
      "executiveSummary.highlights",
      "executiveSummary.aiSummary",
    ],
    priority: 0,
    businessQuestion: "What is the one-sentence verdict on this period?",
    decisionUse: "Lets the owner decide whether to act immediately or read the full report.",
    notes: "Always renders if executiveSummary exists. The dark hero card. Never removed.",
  },
  {
    id: "traffic-kpi",
    name: "Traffic KPI card",
    type: "kpi",
    requiredSources: ["ga4"],
    optionalSources: [],
    requiredDataFields: ["trafficOverview.totalSessions"],
    optionalDataFields: ["trafficOverview.totalSessions.previousValue"],
    priority: 1,
    businessQuestion: "Are more people visiting the site than last period?",
    decisionUse: "First signal of whether acquisition is working.",
    notes: "Core card. Always first KPI if GA4 is connected.",
    metricPath: "trafficOverview.totalSessions",
  },
  {
    id: "organic-reach-kpi",
    name: "Organic Reach KPI card",
    type: "kpi",
    requiredSources: ["ga4"],
    optionalSources: [],
    requiredDataFields: ["trafficOverview.organicSessions"],
    optionalDataFields: ["trafficOverview.organicSessions.previousValue"],
    priority: 2,
    businessQuestion: "Is organic traffic growing without paid spend?",
    decisionUse: "Shows whether SEO effort is compounding over time.",
    notes: "Core card. Separate from total traffic to show SEO health distinctly.",
    metricPath: "trafficOverview.organicSessions",
  },
  {
    id: "search-clicks-kpi",
    name: "Search Clicks KPI card",
    type: "kpi",
    requiredSources: ["gsc"],
    optionalSources: [],
    requiredDataFields: ["seoOverview.totalClicks"],
    optionalDataFields: ["seoOverview.totalClicks.previousValue"],
    priority: 3,
    businessQuestion: "Are people clicking through from search results?",
    decisionUse: "CTR signal - visibility alone isn't enough, clicks matter.",
    notes: "Core card. Only renders if GSC is connected.",
    metricPath: "seoOverview.totalClicks",
  },
  {
    id: "engagement-kpi",
    name: "Engagement KPI card",
    type: "kpi",
    requiredSources: ["ga4"],
    optionalSources: [],
    requiredDataFields: ["trafficOverview.bounceRate"],
    optionalDataFields: ["trafficOverview.bounceRate.previousValue"],
    priority: 4,
    businessQuestion: "Are visitors staying and engaging, or leaving immediately?",
    decisionUse: "Quality signal - high bounce rate means acquisition is working but landing experience isn't.",
    notes: "Core card. Label: \"Engagement\" in the UI. Underlying metric is GA4 engagement rate (inverse of bounce rate). trendGood = false for bounce rate direction.",
    metricPath: "trafficOverview.bounceRate",
  },
  {
    id: "conversions-kpi",
    name: "Conversions KPI card",
    type: "kpi",
    requiredSources: ["ga4"],
    optionalSources: ["google_ads"],
    requiredDataFields: ["conversions.totalConversions"],
    optionalDataFields: [
      "conversions.conversionRate",
      "conversions.totalConversions.previousValue",
    ],
    priority: 5,
    businessQuestion: "Is traffic turning into leads or sales?",
    decisionUse: "Most direct signal of whether digital activity creates business value.",
    notes: "Core card. Only renders if conversions data exists. If missing but GA4 is connected, this is a candidate for the missing-context nudge on the recommendations slide - but NOT on the dashboard (too much friction).",
    metricPath: "conversions.totalConversions",
    secondaryMetricPaths: ["conversions.conversionRate"],
  },
  {
    id: "paid-efficiency-kpi",
    name: "Paid Efficiency KPI card",
    type: "kpi",
    requiredSources: ["google_ads"],
    optionalSources: [],
    requiredDataFields: ["paidOverview.totalSpend"],
    optionalDataFields: ["paidOverview.roas", "paidOverview.costPerConversion"],
    priority: 6,
    businessQuestion: "Is the paid budget delivering efficient returns?",
    decisionUse: "Drives budget reallocation decisions.",
    notes: "Core card. Only renders if Google Ads is connected. Never renders a broken paid card when Ads is not connected.",
    metricPath: "paidOverview.totalSpend",
    secondaryMetricPaths: ["paidOverview.roas", "paidOverview.costPerConversion"],
  },
  {
    id: "sessions-over-time",
    name: "Sessions Over Time chart",
    type: "chart",
    requiredSources: ["ga4"],
    optionalSources: [],
    requiredDataFields: ["trafficOverview.timeSeries"],
    optionalDataFields: [],
    priority: 7,
    businessQuestion: "What did the traffic trend look like across the period?",
    decisionUse: "Spots spikes, dips, and patterns that the KPI number alone hides.",
    notes: "Core section. Narrative sentence above the chart is mandatory in full variant - the chart never stands alone without a \"so what?\" line.",
  },
  {
    id: "channel-breakdown",
    name: "Channel Breakdown",
    type: "section",
    requiredSources: ["ga4"],
    optionalSources: [],
    requiredDataFields: ["trafficOverview.channelBreakdown"],
    alternativeRequiredDataFields: {
      fields: [
        "trafficOverview.organicSessions",
        "trafficOverview.paidSessions",
        "trafficOverview.directSessions",
      ],
      minPresent: 2,
      description:
        "trafficOverview.channelBreakdown or at least two of organicSessions, paidSessions, directSessions",
    },
    optionalDataFields: ["trafficOverview.referralSessions"],
    priority: 8,
    businessQuestion: "Where is traffic coming from - and which channel is carrying the most weight?",
    decisionUse: "Helps decide where to invest more or pull back.",
    notes: "Core section. Always paired with Sessions Over Time in the same visual band if possible.",
  },
  {
    id: "search-visibility",
    name: "Search Visibility grid",
    type: "section",
    requiredSources: ["gsc"],
    optionalSources: [],
    requiredDataFields: [
      "seoOverview.totalClicks",
      "seoOverview.totalImpressions",
      "seoOverview.avgCtr",
      "seoOverview.avgPosition",
    ],
    optionalDataFields: [],
    priority: 9,
    businessQuestion: "Is the site becoming more or less visible in search?",
    decisionUse: "Drives decisions on content, meta descriptions, and keyword targeting.",
    notes: "Core section. Only renders if GSC is connected and all four fields exist. If fewer than four fields exist, drops to simplified or does not render.",
  },
  {
    id: "paid-performance",
    name: "Paid Performance section",
    type: "section",
    requiredSources: ["google_ads"],
    optionalSources: [],
    requiredDataFields: ["paidOverview.totalSpend", "paidOverview.totalClicks"],
    optionalDataFields: [
      "paidOverview.roas",
      "paidOverview.avgCpc",
      "paidOverview.conversions",
    ],
    priority: 10,
    businessQuestion: "How is the paid budget performing in detail?",
    decisionUse: "Gives enough paid detail to have an informed conversation about campaign efficiency.",
    notes: "Contextual section. Only renders if Google Ads is connected. Complements the Paid KPI card with more detail.",
  },
];

export function getDashboardDefinitionById(id: string): DashboardDefinition | undefined {
  return dashboardRegistry.find((item) => item.id === id);
}
